import type { Article } from './types';

export const articles: Article[] = [
  {
    id: '1',
    slug: 'tendencias-otono-invierno-2024',
    title: 'Las Claves de Estilo para Otoño/Invierno 2024',
    excerpt: 'Descubre las tendencias que dominarán la temporada, desde abrigos oversize hasta botas de combate.',
    publishedDate: '2024-09-15',
    category: 'Temporadas',
    imageId: 'article-1',
  },
  {
    id: '2',
    slug: 'el-regreso-de-los-accesorios-maxi',
    title: 'El Regreso Triunfal de los Accesorios Maxi',
    excerpt: 'Los pendientes XL, los collares audaces y los bolsos llamativos están de vuelta. Te contamos cómo llevarlos.',
    publishedDate: '2024-09-12',
    category: 'Accesorios',
    imageId: 'article-2',
  },
  {
    id: '3',
    slug: 'cinco-tips-para-un-armario-sostenible',
    title: '5 Tips para un Armario Cápsula y Sostenible',
    excerpt: 'Construye un guardarropa versátil y eco-consciente con estas sencillas claves de estilo y consumo.',
    publishedDate: '2024-09-10',
    category: 'Tips',
    imageId: 'article-3',
  },
  {
    id: '4',
    slug: 'guia-de-estilo-minimalista-moderno',
    title: 'Guía de Estilo: El Minimalismo Moderno',
    excerpt: 'Menos es más. Aprende a dominar el arte del minimalismo con prendas de calidad y siluetas limpias.',
    publishedDate: '2024-09-08',
    category: 'Moda',
    imageId: 'article-4',
  },
  {
    id: '5',
    slug: 'rituales-de-bienestar-para-tu-dia-a-dia',
    title: 'Rituales de Bienestar para Integrar en tu Día a Día',
    excerpt: 'Pequeños hábitos que marcan una gran diferencia en tu estado de ánimo y energía. Desde el mindfulness hasta el cuidado de la piel.',
    publishedDate: '2024-09-05',
    category: 'Estilo de vida',
    imageId: 'article-5',
  },
  {
    id: '6',
    slug: 'los-colores-que-marcaran-la-primavera',
    title: 'Los Colores que Marcarán la Próxima Primavera',
    excerpt: 'Adelántate a la próxima temporada con la paleta de colores que verás por todas partes.',
    publishedDate: '2024-09-02',
    category: 'Temporadas',
    imageId: 'article-6',
  },
  {
    id: '7',
    slug: 'bolsos-iconicos-que-son-una-inversion',
    title: 'Bolsos Icónicos que Son una Inversión Eterna',
    excerpt: 'Exploramos los diseños que nunca pasan de moda y por qué valen la pena.',
    publishedDate: '2024-08-28',
    category: 'Accesorios',
    imageId: 'article-7',
  },
  {
    id: '8',
    slug: 'como-cuidar-tus-prendas-de-lino',
    title: 'Tips Esenciales para Cuidar tus Prendas de Lino',
    excerpt: 'Mantén tus prendas favoritas de lino como nuevas con estos consejos de lavado y almacenamiento.',
    publishedDate: '2024-08-25',
    category: 'Tips',
    imageId: 'article-8',
  },
  {
    id: '9',
    slug: 'el-arte-de-vestir-monocromatico',
    title: 'El Arte de Vestir Monocromático con Éxito',
    excerpt: 'Domina los looks de un solo color para un estilo sofisticado y sin esfuerzo.',
    publishedDate: '2024-08-22',
    category: 'Moda',
    imageId: 'article-9',
  },
  {
    id: '10',
    slug: 'destinos-de-viaje-con-estilo',
    title: 'Destinos de Viaje que Inspiran Estilo y Aventura',
    excerpt: 'Lugares que no solo ofrecen paisajes increíbles, sino también una rica cultura de moda y diseño.',
    publishedDate: '2024-08-19',
    category: 'Estilo de vida',
    imageId: 'article-10',
  },
  {
    id: '11',
    slug: 'el-poder-del-blazer-perfecto',
    title: 'El Poder del Blazer: Cómo Encontrar el Corte Perfecto',
    excerpt: 'Una pieza clave en cualquier armario. Te ayudamos a elegir el que mejor se adapte a ti.',
    publishedDate: '2024-08-15',
    category: 'Moda',
    imageId: 'article-11',
  },
  {
    id: '12',
    slug: 'decoracion-slow-living',
    title: 'Slow Living: Ideas para un Hogar en Calma',
    excerpt: 'Crea un santuario de paz en casa con principios de diseño que promueven la tranquilidad.',
    publishedDate: '2024-08-11',
    category: 'Estilo de vida',
    imageId: 'article-12',
  },
];

export const categories: { name: Article['category'] }[] = [
    { name: 'Moda' },
    { name: 'Estilo de vida' },
    { name: 'Tips' },
    { name: 'Accesorios' },
    { name: 'Temporadas' },
];
